### ISSUE TITLE
clean command not detecting versions properly

### ISSUE THREAD

**Issue by philippevezina** [ElMassimo/vite_ruby#438] opened 2024-03-05 19:40 UTC
### Description 📖

`vite_ruby` uses the `mtime` as a reference to detect different versions of the app: https://github.com/ElMassimo/vite_ruby/blob/main/vite_ruby/lib/vite_ruby/commands.rb#L148 That being said, a single Vite build can generate files with more than one `mtime`. For example, `vite-plugin-rails` uses `rollup-plugin-gzip` at the end of the build which will write many files with different `mtime`s.

This causes files to delete unexpectedly when running `bin/vite clean`. It's possible this bug is hard to reproduce with a small project as all written files may end up having the same `mtime`.

### Reproduction 🐞

<details>
<summary>Vite Ruby Info</summary>

- Run `bin/rake vite:build` on a big project with no currently built assets.
- Run `bin/rake vite:clean[1,0]`

Result: files will be deleted while there is only a single version of the built assets.
</details>

**Comment by ElMassimo** [comment] 2024-03-26 14:37
Hi Philippe, thanks for reporting!

Fixing this will likely require grouping files by modified time using a certain range (maybe 5 minutes is a reasonable default).

**Comment by benlangfeld** [comment] 2024-07-04 17:02
This is a duplicate of #404, right?

**Comment by benlangfeld** [comment] 2024-07-04 18:13
Fix proposed in #477 which mirrors the behaviour of vite_ruby before a recent tangentially related bugfix, as well as Webpacker.

**Comment by philippevezina** [comment] 2024-07-05 14:00
> Fix proposed in #477 which mirrors the behaviour of vite_ruby before a recent tangentially related bugfix, as well as Webpacker.

This PR won't fix the issue described here. The issue still remains that Vite Ruby relies on common `mtime`s on files to determine the set of files belonging to a certain version. That said, when trying to keep 2 versions of the assets, the returned files may all belong to only a single build rather than 2 because the `mtime` could be 1 second off for some files.

**Comment by benlangfeld** [comment] 2024-07-05 14:02
> > Fix proposed in #477 which mirrors the behaviour of vite_ruby before a recent tangentially related bugfix, as well as Webpacker.
> 
> This PR won't fix the issue described here. The issue still remains that Vite Ruby relies on common `mtime`s on files to determine the set of files belonging to a certain version. That said, when trying to keep 2 versions of the assets, the returned files may all belong to only a single build rather than 2 because the `mtime` could be 1 second off for some files.

Ok, but it will fix guaranteeing you retain at least the most recent version.

**Closed** 2024-08-12 13:38 UTC
Labels: bug, help wanted
