### ISSUE TITLE
Vitest fails when using vite-plugin-ruby

### ISSUE THREAD

**Issue by timgoeller** [ElMassimo/vite_ruby#170] opened 2022-01-04 08:57 UTC
[troubleshooting section]: https://vite-ruby.netlify.app/guide/troubleshooting.html

- [x] I have tried upgrading by running `bundle update vite_ruby`.
- [x] I have read the __[troubleshooting section]__ before opening an issue.

### Description 📖

When adding the `vite-plugin-ruby` in the `vite.config.js`, `vitest` fails. It works when removing `vite-plugin-ruby`, and it also works with non-Vue tests. It fails with the error `failed to load /vite-development/@vite/client`.

### Reproduction 🐞

https://stackblitz.com/edit/node-sr8dj2?file=vite.config.js

### Screenshots 📷

![image](https://user-images.githubusercontent.com/10633973/148034069-4f3fce3e-0972-4a68-87c0-de960101bac8.png)

**Comment by ElMassimo** [comment] 2022-01-04 11:07
Hi Tim, thanks for reporting.

It's probably related with the use of `base`, which might not have been tested in `vitest`, since it's only common for backend integrations.

Similar to [this issue in unocss](https://github.com/antfu/unocss/issues/254#issuecomment-1003707746).

Try setting `publicOutputDir` to an empty string in development. If it works, please open an issue in Vitest, otherwise I'll take a look during the week.

**Comment by ElMassimo** [comment] 2022-01-04 21:43
Closing as it was [confirmed](https://github.com/vitest-dev/vitest/issues/436) to be related to how Vitest handles `base`.

**Closed by ElMassimo** 2022-01-04 21:43 UTC
Labels: bug

**Comment by AlvesJorge** [comment] 2024-10-21 14:12
I started getting this error after upgrading to vite 5, and vitest/* to 2.
Changing `publicOutputDir` to an empty string in the test env in `vite.json` indeed fixes this. But I wonder if there's a way to config vitest to use the correct path?

**Comment by AlvesJorge** [comment] 2024-10-22 08:38
Changing `publicOutputDir` to an empty string causes problems when running my rspec tests, since "something" (most likely vite) tries to clear this directory when the tests are finished. Instead I added the flag directly to my `package.json` test command, and left `vite.json` as it was.
`NODE_ENV=test VITE_RUBY_PUBLIC_OUTPUT_DIR='' vitest`

**Comment by ElMassimo** [comment] 2024-10-22 13:13
@AlvesJorge I'm using `vitest` since `0.18.1`, and I haven't run into any issues.

Please open a new ticket, and add a minimal reproduction, ideally a new Rails app.
