### ISSUE TITLE
TCP connection descriptors leak

### ISSUE THREAD

**Issue by vladimirtemnikov** [ElMassimo/vite_ruby#219] opened 2022-06-18 05:39 UTC
[troubleshooting section]: https://vite-ruby.netlify.app/guide/troubleshooting.html

- [x] I have tried upgrading by running `bundle update vite_ruby`.
- [x] I have read the __[troubleshooting section]__ before opening an issue.

### Description 📖

Hello, @ElMassimo, I hope you are fine! 😄 

Currently I'm using `vite-rails` in our team's project, especially with puma server in dev. Such a pleasure 😍 !
There is a huge bunch of es modules to request on pages, so I've found this issue pretty fast.

I'm not sure where is the root cause of the problem, but it sounds like `rack-proxy` does not provide the right way to close streaming TCP connections.

When I reload the page, my assets are cached, so vite server returns 304 status code.
Puma optimizes this case and doesn't go through a response's IO, which is provided by "hacked net/http" wrapper `Rack::HttpStreamingResponse` from `rack-proxy`. I'm not even sure that this is wrong, because a `Rack::HttpStreamingResponse` should normally implement `#close` method, but `rack-proxy` can only close TCP connection if `Rack::HttpStreamingResponse#each` was called 🤔.

As a result, the sockets will never gone, they only disappear with puma's process shutdown, so I get an `too many opened files` error very fast 😄.

### Reproduction 🐞

Currently I have no suitable repo to reproduce, but problem shows itself with any setup of `rails` with `puma`.

As an example after first page load:

```
> lsof -i -n -P | grep "127.0.0.1:3036"

ruby       4703 vladimirtemnikov   24u  IPv4 0x90a678847d0ffff      0t0  TCP 127.0.0.1:58368->127.0.0.1:3036 (CLOSE_WAIT)
ruby       4703 vladimirtemnikov   31u  IPv4 0x90a67884b377637      0t0  TCP 127.0.0.1:58372->127.0.0.1:3036 (CLOSE_WAIT)
ruby       4703 vladimirtemnikov   34u  IPv4 0x90a67884b376b5f      0t0  TCP 127.0.0.1:58373->127.0.0.1:3036 (CLOSE_WAIT)
ruby       4703 vladimirtemnikov   35u  IPv4 0x90a67884e663637      0t0  TCP 127.0.0.1:58375->127.0.0.1:3036 (CLOSE_WAIT)
ruby       4703 vladimirtemnikov   38u  IPv4 0x90a67884c2755af      0t0  TCP 127.0.0.1:58382->127.0.0.1:3036 (CLOSE_WAIT)
ruby       4703 vladimirtemnikov   40u  IPv4 0x90a67884b374ad7      0t0  TCP 127.0.0.1:58381->127.0.0.1:3036 (CLOSE_WAIT)
ruby       4703 vladimirtemnikov   42u  IPv4 0x90a67884e664be7      0t0  TCP 127.0.0.1:58386->127.0.0.1:3036 (CLOSE_WAIT)
ruby       4703 vladimirtemnikov   43u  IPv4 0x90a67884b3796bf      0t0  TCP 127.0.0.1:58385->127.0.0.1:3036 (CLOSE_WAIT)
ruby       4703 vladimirtemnikov   44u  IPv4 0x90a67884b378be7      0t0  TCP 127.0.0.1:58388->127.0.0.1:3036 (CLOSE_WAIT)
ruby       4703 vladimirtemnikov   45u  IPv4 0x90a67884e64cad7      0t0  TCP 127.0.0.1:58390->127.0.0.1:3036 (CLOSE_WAIT)
ruby       4703 vladimirtemnikov   46u  IPv4 0x90a678847bbf637      0t0  TCP 127.0.0.1:58392->127.0.0.1:3036 (CLOSE_WAIT)
ruby       4703 vladimirtemnikov   47u  IPv4 0x90a678847d13637      0t0  TCP 127.0.0.1:58394->127.0.0.1:3036 (CLOSE_WAIT)
ruby       4703 vladimirtemnikov   48u  IPv4 0x90a67884b376087      0t0  TCP 127.0.0.1:58409->127.0.0.1:3036 (CLOSE_WAIT)
ruby       4703 vladimirtemnikov   49u  IPv4 0x90a6788481d8be7      0t0  TCP 127.0.0.1:58411->127.0.0.1:3036 (CLOSE_WAIT)
ruby       4703 vladimirtemnikov   50u  IPv4 0x90a678848b3eb5f      0t0  TCP 127.0.0.1:58413->127.0.0.1:3036 (CLOSE_WAIT)
ruby       4703 vladimirtemnikov   51u  IPv4 0x90a67884e6516bf      0t0  TCP 127.0.0.1:58415->127.0.0.1:3036 (CLOSE_WAIT)
ruby       4703 vladimirtemnikov   52u  IPv4 0x90a67884e64b527      0t0  TCP 127.0.0.1:58417->127.0.0.1:3036 (CLOSE_WAIT)
```

... and after persistence timeout ends their status is switched to CLOSED, but descriptors are still there... Unfortunately 😢 

What will be better way to fix this problem? I'm ready to contribute 😄 

<details>
<summary>Vite Ruby Info</summary>

```
bin/vite present?: true
vite_ruby: 3.1.6
vite_rails: 3.0.10
rails: 6.1.6
node: v16.15.1
npm: 8.11.0
yarn: 3.2.1
pnpm: Usage Error: This project is configured to use yarn

$ pnpm ...
ruby: ruby 2.7.6p219 (2022-04-12 revision c9c2245c0a) [arm64-darwin21]

installed packages:
core@ /Users/vladimirtemnikov/ActivePlatform/clean_core
├─┬ unplugin-vue-components@0.19.6
│ └─┬ unplugin@0.6.3
│   └── vite@2.9.12 deduped
├─┬ vite-plugin-erb@1.1.0
│ └── vite@2.9.12 deduped
├─┬ vite-plugin-ruby@3.0.12
│ └── vite@2.9.12 deduped
├─┬ vite-plugin-vue2@2.0.1
│ └── vite@2.9.12 deduped
└── vite@2.9.12
```
</details>

**Comment by ElMassimo** [comment] 2022-06-18 14:54
Hi Vladimir, thanks for reporting!

A [similar but unrelated issue](https://vite-ruby.netlify.app/guide/troubleshooting.html#requests-to-vite-sporadically-return-a-500-error-response) can occur then the maximum amount of open file descriptors in the OS is too low.

As a workaround, I would suggest **increasing the maximum amount of file descriptors**, which has a low default in some operating systems.

It's a *temporary* workaround—the amount of open sockets would keep growing and could eventually hit the limit—but it should give you more time between server restarts.

---

Please share the versions of `puma` and `rack-proxy` that you are using, as well as the OS version, and the maximum amount of file descriptors in your system.

It's likely that the fix needs to happen upstream in `rack-proxy` or `puma`, so you might want to look in the issue tracker for these libraries, and open an issue that links back to this use case.

If there's a workaround that can be applied in this project, let's discuss it.

**Comment by vladimirtemnikov** [comment] 2022-06-18 15:58
@ElMassimo I use `puma` 5.6.4, `rack-proxy` 0.7.2, it's edge version problem, using macOS Monterey, max amount is 10240.

Increasing max limit does not help much.
I currently disabled streaming mode with monkey-patch, works perfectly.

I'm afraid `rack-proxy` is not maintained well, but I could try create an issue there.

**Comment by ElMassimo** [comment] 2022-06-18 16:33
After a quick look [at the `puma` optimization](https://cs.github.com/puma/puma/blob/6a5bda5b4eeb8c86c64468d6916f7d3917e5640a/lib/puma/request.rb?q=%3Ano_body#L125) for the [304 status](https://cs.github.com/puma/puma/blob/6a5bda5b4eeb8c86c64468d6916f7d3917e5640a/lib/puma/request.rb?q=STATUS_WITH_NO_ENTITY_BODY#L417) and the [`rack-proxy` streaming response](https://github.com/ncr/rack-proxy/blob/master/lib/rack/http_streaming_response.rb#L21), I think the fix involves immediately closing the `Net::HTTP` connection when the status code is 204, 205, or 304.

Something along the lines of:

```ruby
def code
  response.code.to_i.tap do |code|
    set_no_response if STATUS_WITH_NO_ENTITY_BODY[code]
  end
end
```

Where `set_no_response` can do:

```ruby
def set_no_response
  @no_response = true
ensure
  session.end_request_hacked
  session.finish
end
```
and `each` is changed to be a no-op when `@no_response` is set.

Feel free to make a PR to `rack-proxy` with this idea, I currently don't have access to a computer.

**Comment by ElMassimo** [comment] 2022-06-18 16:35
Closing as we confirmed it's not related with the way `vite_ruby` uses `rack-proxy`, but due to the interaction between `puma` and `rack-proxy`'s streaming responses.

**Closed by ElMassimo** 2022-06-18 16:35 UTC
Labels: bug: pending triage

**Comment by vladimirtemnikov** [comment] 2022-06-18 16:38
Thank you for you quick response! I'll communicate with `rack-proxy` maintainer soon.
